### ISSUE TITLE
[Bug] Incorrect behavior when template contains a

### ISSUE THREAD

**Issue by HeroicEric** [gitKrystan/prettier-plugin-ember-template-tag#222] opened 2024-01-05 20:37 UTC
### 🐞 Describe the Bug

Components are not formatted correctly when `<template>` contains unicode characters such as `✓` or `©` rather than `&check;` or `&copy;`.

### 🔬 Minimal Reproduction

Failing test added in https://github.com/gitKrystan/prettier-plugin-ember-template-tag/pull/221

```gts
import Component from '@glimmer/component';

export interface Signature {
  Element: HTMLElement,
  Args: {}
  Yields: []
}

/** It's a component */
class MyComponent extends Component<Signature> {
  <template>
    ✓
  </template>
}

function hello() {
  return 'Hello';
}

function world() {
  return 'World';
}
```

### 😕 Actual Behavior

```gts
import Component from "@glimmer/component";

export interface Signature {
  Element: HTMLElement;
  Args: {};
  Yields: [];
}

/** It's a component */
class MyComponent extends Component<Signature> {
  <template>✓</template>
}
function hello() {
  return "Hello";
}
function world() {
  return "World";
}
```

Note: The newlines are removed between the helper functions.

### 🤔 Expected Behavior

```gts
import Component from "@glimmer/component";

export interface Signature {
  Element: HTMLElement;
  Args: {};
  Yields: [];
}

/** It's a component */
class MyComponent extends Component<Signature> {
  <template>✓</template>
}

function hello() {
  return "Hello";
}

function world() {
  return "World";
}
```

### 🌍 Environment

- prettier-plugin-ember-template-tag version: 2.0.0
- ember-template-imports version (if applicable): 4.0.0
- content-tag version (if applicable): 1.2.2
- eslint-plugin-ember version (if applicable): 12.0.0-alpha.4

### ➕ Additional Context

Replacing the direct symbols with the HTML entity codes like `&check;` fixes the formatting issue (and is preferred anyway)

**Comment by gitKrystan** [comment] 2024-01-05 21:30
Thanks for the report! This sounds like a duplicate of https://github.com/gitKrystan/prettier-plugin-ember-template-tag/issues/191

**Closed by gitKrystan** 2024-01-05 21:30 UTC
