### ISSUE TITLE
[Bug] Emoji in JS code breaking plugin

### ISSUE THREAD

**Issue by lifeart** [gitKrystan/prettier-plugin-ember-template-tag#238] opened 2024-01-24 15:05 UTC
### 🐞 Describe the Bug

Plugin failing then I'm trying to format `.gts` file with emojis.

### 🔬 Minimal Reproduction

```gts
test('it works with args [fallback]', async function (assert) {
    const H4 = <template>
      <h4>
        <span style='margin: 0px 10px 0px 10px'>{{if
            @text
            @text
            'To do'
          }}</span>
      </h4>
    </template>;
    await render(<template><H4 /></template>);
    assert.dom().hasText('🚧To do');
  });
```

### 😕 Actual Behavior

Error: 
```stack
[error] src/tests/integration/if-test.gts: Error: failed to process all templates, 10 remaining
[error]     at convertAst (file:///Users/lifeart/Repos/glimmer-next/node_modules/.pnpm/prettier-plugin-ember-template-tag@2.0.0_prettier@3.1.1/node_modules/prettier-plugin-ember-template-tag/dist/prettier-plugin-ember-template-tag.js:70060:11)
[error]     at Object.parse (file:///Users/lifeart/Repos/glimmer-next/node_modules/.pnpm/prettier-plugin-ember-template-tag@2.0.0_prettier@3.1.1/node_modules/prettier-plugin-ember-template-tag/dist/prettier-plugin-ember-template-tag.js:70079:5)
[error]     at async parse (file:///Users/lifeart/Repos/glimmer-next/node_modules/.pnpm/prettier@3.1.1/node_modules/prettier/index.mjs:19362:11)
[error]     at async coreFormat (file:///Users/lifeart/Repos/glimmer-next/node_modules/.pnpm/prettier@3.1.1/node_modules/prettier/index.mjs:20683:7)
[error]     at async formatWithCursor (file:///Users/lifeart/Repos/glimmer-next/node_modules/.pnpm/prettier@3.1.1/node_modules/prettier/index.mjs:20885:14)
[error]     at async formatFiles (file:///Users/lifeart/Repos/glimmer-next/node_modules/.pnpm/prettier@3.1.1/node_modules/prettier/internal/cli.mjs:7073:18)
[error]     at async main (file:///Users/lifeart/Repos/glimmer-next/node_modules/.pnpm/prettier@3.1.1/node_modules/prettier/internal/cli.mjs:7279:5)
[error]     at async Module.run (file:///Users/lifeart/Repos/glimmer-next/node_modules/.pnpm/prettier@3.1.1/node_modules/prettier/internal/cli.mjs:7225:5)
```

### 🤔 Expected Behavior

Plugin should work fine with emojis.

### 🌍 Environment

- prettier-plugin-ember-template-tag version: - 2.0.0

**Comment by gitKrystan** [comment] 2024-01-24 17:43
Duplicate of #191

**Closed by gitKrystan** 2024-01-24 17:43 UTC
